// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnhF97eTnmiVgFkWzBd9t64qc6yypEwp0',
    appId: '1:44570150142:web:030d8fc66eb04c5b0d11af',
    messagingSenderId: '44570150142',
    projectId: 'electrosign-877ff',
    authDomain: 'electrosign-877ff.firebaseapp.com',
    storageBucket: 'electrosign-877ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7oej9NMVIrrdszZ-Mx0oZZtMxry-wAg',
    appId: '1:44570150142:android:5bd0a94817c1bacd0d11af',
    messagingSenderId: '44570150142',
    projectId: 'electrosign-877ff',
    storageBucket: 'electrosign-877ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArlLFmCQJXeoySSuwff339GT7eBSwxgl4',
    appId: '1:44570150142:ios:78e7679aa428b7e10d11af',
    messagingSenderId: '44570150142',
    projectId: 'electrosign-877ff',
    storageBucket: 'electrosign-877ff.appspot.com',
    iosBundleId: 'com.example.electrosign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArlLFmCQJXeoySSuwff339GT7eBSwxgl4',
    appId: '1:44570150142:ios:78e7679aa428b7e10d11af',
    messagingSenderId: '44570150142',
    projectId: 'electrosign-877ff',
    storageBucket: 'electrosign-877ff.appspot.com',
    iosBundleId: 'com.example.electrosign',
  );
}
